# sops configuration
# run `make check-age-key` to check if age key exists
# run `make generate-key` to create new age key
# run `make setup-sops` to configure .sops.yaml
creation_rules:
  - path_regex: (^|.*/)\.env(\..*\.local)?$
    key_groups:
      - age:
          - age14vt4dpyvf82qarh3j8efjzyzqynjgu4yyu5ecgfx65nrufjjfyzqe9kuy9
